# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1mfiYx_B9ujDzup-64j-ixYUFDTie0g
"""

FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod init project4 && \
    go get golang.org/x/net/html

RUN go build -o extract_tables .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/extract_tables .

RUN chmod +x extract_tables

RUN mkdir -p output

ENTRYPOINT ["./extract_tables"]